name: house_buddy_mon
description: Pokemon-styled shared-home manager
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  http: ^1.2.2
  provider: ^6.1.2

flutter:
  uses-material-design: true
